version: "3"

services:
  mariadb:
    image: mariadb:10.6
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--host=localhost",
          "--port=$MYSQL_TCP_PORT",
          "--user=$MYSQL_USER",
          "--password=$MYSQL_PASSWORD",
        ]
      timeout: 5s
      retries: 3
    networks:
      - talk_me
    ports:
      - $MYSQL_TCP_PORT:$MYSQL_TCP_PORT
    restart: always
    volumes:
      - ./database:/var/lib/mysql

networks:
  talk_me:
    name: talk_me
